robust tests
EasyPost/easypost-node pull request #304
Opened 2022-10-07 21:31 UTC by Justintime50

# Description

- Boost test coverage from ~75% to ~90%
- Enforces coverage
- Adds nested cassette scrubbing (cannot at present scrub CC details due to how Pollyjs works)
- Billing tests are still skipped for now as I've burned our allotted time on this task. Can revisit when this library gets its thread-safe rewrite (didn't have time to dig into mocking)
- Fixed the following bugs:
    - Fixes multiple bugs that made the `addCreditCard` function unusable, adds tests
    - The response of the `updateBrand` function now properly becomes a `Brand` object
    - Insuring a shipment via `Shipment.insure` no longer improperly wraps the `amount` key in `id`. There may be other edge cases among other object/function calls that get corrected due to this change
    - Validating webhook signatures of differing byte sizes now throws a more meaningful error message

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2022-10-11 21:48 UTC, Justintime50 commented on src/resources/base.js
>  import NotImplementedError from '../errors/not_implemented';
# Reviewer Note

Most of the changes in this file were simply organization and did not adjust logic as it was previously near impossible to reason about what things were where as there were similar functions spread all over this file.

2022-10-11 22:57 UTC, nwithan8 requested changes

2022-10-11 22:57 UTC, nwithan8 commented on CHANGELOG.md
> +- Fixes multiple bugs that made the `addCreditCard` function unusable, adds tests
I'm not seeing any diff lines here re: changing this function. Can you point me to them?

2022-10-11 22:58 UTC, nwithan8 approved these changes

2022-10-12 17:06 UTC, jchen293 approved these changes

2022-10-12 17:13 UTC, merged