feat: Add functions to retrieve event payload(s)
EasyPost/easypost-node pull request #330
Opened 2023-01-17 19:40 UTC by nwithan8

# Description

- New static functions to retrieve payload(s) for an event
- New Payload model and TypeScript definition
- New unit tests, cassettes to test payload functions
- New recordings for other event unit tests (oops)
- Improvements to docstrings

Since a Payload object does not have any instance functions (and as a small POC of the upcoming redesign), the Payload class does not extend the base class. As a result, there are a handful of functions (e.g. construction from JSON) that had to be ported out of the base class and re-implemented in the Payload class. It was either that, or extend the base class and override the various instance functions (`save`, `delete`, `all`) to not be implemented. In my opinion, this is a cleaner, safer approach.

The JSON of the response to retrieving all payloads technically returns an object with a single `payloads` key, like so:

```json
{
  "payloads": []
}
```

If this object were deserialized exactly, it would actually create a PayloadsCollection object (similar to what we do with Shipment Collection, Tracker Collection, etc. in type-strict languages). The actual Payload objects would be accessed by `payloads = payloadCollection.payloads`. This makes sense when the results are paginated, and the collection has more than one key (`has_more`). But since Payloads are not paginated, this doesn't make much sense. Instead, the retrieve all function remaps the data to simply return an array of Payload objects, which is easier to work with for the end-user and more accurately matches expectations.

# Testing

- New unit tests, cassettes
-
# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2023-01-17 21:50 UTC, Justintime50 requested changes
I don't see that the payload prop types were ever added to the global constant `PROP_TYPES`. Please do that here.

2023-01-17 22:57 UTC, nwithan8 commented
> I don't see that the payload prop types were ever added to the global constant `PROP_TYPES`. Please do that here.

Not needed, as the base class will never be accessing the properties or Payload class to deserialize (deserialization is done one-off inside the Payload class, not by the base class).

2023-01-18 16:06 UTC, Justintime50 approved these changes
🤨 trusting

2023-01-18 16:50 UTC, jchen293 approved these changes

2023-01-18 16:53 UTC, merged