feat: adds missing properties to Rate model
EasyPost/easypost-node pull request #466
Opened 2024-08-07 15:40 UTC by Justintime50

# Description

# Testing

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2024-08-07 15:41 UTC, nwithan8 approved these changes

2024-08-07 15:50 UTC, jchen293 submitted a review, later dismissed

2024-08-07 16:43 UTC, nwithan8 requested changes
Add TS definitions for Rate and Surcharge

2024-08-08 19:43 UTC, nwithan8 approved these changes

2024-08-08 19:44 UTC, merged